# Generated by Django 3.0.7 on 2020-07-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmaster', '0003_settingsmodel_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetmodel',
            name='followed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='targetmodel',
            name='unfollowed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
