# Generated by Django 3.0.7 on 2020-07-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmaster', '0006_auto_20200724_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsmodel',
            name='emailsuspicion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
